const dotenv = {
  AUTHENTICATION_APP_PORT: "AUTHENTICATION_APP_PORT",
  AUTHENTICATION_APP_HOST: "AUTHENTICATION_APP_HOST",
  AUTHENTICATION_APP_JWT_SECRET: "AUTHENTICATION_APP_JWT_SECRET",
  GOOGLE_CLIENT_ID: "GOOGLE_CLIENT_ID",
  FACEBOOK_CLIENT_ID: "FACEBOOK_CLIENT_ID",
};

export default dotenv;
